services:
  app:
    image: ${IMAGE_URI}
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      OLLAMA_BASE_URL: ${OLLAMA_URL}
    restart: always
    networks:
      - bankapp-network

networks:
  bankapp-network:
    driver: bridge
