apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: default
type: Opaque
stringData:
  mysql-root-password: "Wajih@BankApp#2026"
  mysql-database: "bankappdb"
  mysql-user: "WAJIH"
  ollama-url: "http://172.31.38.136:11434"
